web:
  build: .
  external_links:
    - getyiifrontend_mysql_1:mysql
  ports:
    - 8081:80
  environment:
    - MYSQL_INSTANCE_NAME=getyii
    - MYSQL_PASSWORD=getyii.com
    - APP_ENV=Production
  volumes:
    - ../getyii-vendor/:/app/vendor:rw
    - ~/.composer/cache:/root/.composer/cache:rw
    - .:/app:rw # you should uncomment this line if you want to develop the app.
